# Generated by Django 4.2.2 on 2023-07-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_workingday_doctor_working_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='WorkingDay',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='working_days',
            field=models.ManyToManyField(related_name='doctors', to='users.day'),
        ),
    ]
