# Generated by Django 4.2.2 on 2023-07-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_day_delete_workingday_alter_doctor_working_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
