# Generated by Django 4.2.2 on 2023-07-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_day_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='working_days',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_days',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
