# Generated by Django 4.2.2 on 2023-07-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_doctor_working_days_delete_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='working_days',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
